export const FORD_COLORS = {
  FORD_BLUE: '#1B448C',
  FORD_DARK_BLUE: '#0D2240',
  FORD_LIGHT_BLUE: '#4A7BB7',

  FORD_SILVER: '#8C8D8F',
  FORD_CHARCOAL: '#2D2D2D',

  HEALTH_NORMAL: '#2E7D32',
  HEALTH_ATTENTION: '#F57C00',
  HEALTH_CRITICAL: '#C62828',

  WHITE: '#FFFFFF',
  LIGHT_GRAY: '#F5F5F5',
  MEDIUM_GRAY: '#E0E0E0',
  DARK_GRAY: '#757575',
  BLACK: '#000000',

  SUCCESS: '#4CAF50',
  WARNING: '#FF9800',
  ERROR: '#F44336',
  INFO: '#2196F3',
} as const;

export const SEMANTIC_COLORS = {
  primary: FORD_COLORS.FORD_BLUE,
  secondary: FORD_COLORS.FORD_SILVER,
  background: FORD_COLORS.WHITE,
  surface: FORD_COLORS.LIGHT_GRAY,
  text: FORD_COLORS.FORD_CHARCOAL,
  textSecondary: FORD_COLORS.DARK_GRAY,
  border: FORD_COLORS.MEDIUM_GRAY,
} as const;